config/routes.rb
  Rienscrafts::Application.routes.draw do
  
  root :to => "site#index"
  match '/admin/vhod' => 'admin/menu#index'
  match 'labelitems' => 'site#label_items'  
  match 'groupitems' => 'site#group_items'  
  match 'itemshow' => 'site#item_show'  

  devise_for :users
  
  resources :users, :only => :show
  
  namespace :admin do

    resources :home, :labels, :attr_types, :users

    resources :items do
      collection do
        get 'refresh_group_labels'
      end
    end

  end

   match ':controller(/:action(/:id(.:format)))'
end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_accessible :name, :descr, :price, :group_id, :photos_attributes, :attrs_attributes, :labels_attributes

	validates :name, :presence => true, :length => {:minimum => 4}

	belongs_to :group
	has_many :attrs, :dependent => :destroy
	has_many :photos, :dependent => :destroy
	has_and_belongs_to_many :labels

	accepts_nested_attributes_for :attrs, 
									:reject_if => lambda { |a| a[:detail].blank? },
									:allow_destroy => true

	accepts_nested_attributes_for :photos, 
									:reject_if => lambda { |a| a[:img].blank? },
									:allow_destroy => true

	accepts_nested_attributes_for :labels, 
									:reject_if => lambda { |a| a[:id].blank? },
									:allow_destroy => true

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_filter :authenticate_user!

	respond_to :html, :js

	def index
	    @items = Item.all
	end

	def new
		@item = Item.new
		@group_labels = Label.all		
		2.times { @item.attrs.build }
		@attr_types_map = AttrType.all.map {|at| [at.name, at.id]}
		4.times { @item.photos.build }
	end

	def show
    	@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
		@group_labels = Label.find(:all, :conditions => ['group_id = ?', @item.group.id])
		@item_label_ids = @item.labels.all.collect {|il| il.id}
		2.times { @item.attrs.build }
		@attr_types_map = AttrType.all.map {|at| [at.name, at.id]}
		4.times { @item.photos.build }

	end

    def refresh_group_labels
		@group_labels = Label.find(:all, :conditions => ['group_id = ?', params[:selected_group_id]])
    	item_id = params[:item_id]
    	if (item_id)
	    	@item = Item.find(item_id)
			@item_label_ids = @item.labels.all.collect {|il| il.id}
	    end

    	respond_to do |fmt|
    		fmt.html {render :partial => "group_labels"}
		end

    end
    	
	def create
		@item = Item.create(params[:item])

    	if params[:curr_label_ids]
	    	curr_label_ids = params[:curr_label_ids].keys {|id| id.to_i}
	    end
    	if curr_label_ids
    		curr_label_ids.each do |id|
				@item.labels << Label.find(id)
    		end
    	end    	


	    respond_to do |fmt|
			if @item.save
			   		flash[:notice] = 'Item created.'
		        	fmt.html { redirect_to([:admin, @item]) }
		    else 
		    	flash[:error] = 'Problem saving the item!'
		    	fmt.html { render :action => "new" }
	    	end
        end
 
	end

  	# PUT /items/1
  	def update
    	@item = Item.find(params[:id])

	    if params[:prev_label_ids]
	    	prev_label_ids = params[:prev_label_ids].keys {|id| id.to_i}
	    end    	
    	if params[:curr_label_ids]
	    	curr_label_ids = params[:curr_label_ids].keys {|id| id.to_i}
	    end
	    
    	if prev_label_ids
    		prev_label_ids.each do |id|
    			unless curr_label_ids and curr_label_ids.include?(id)
    				@item.labels.delete Label.find(id)
    			end
    		end
    	end
    	if curr_label_ids
    		curr_label_ids.each do |id|
    			unless prev_label_ids and prev_label_ids.include?(id)
    				@item.labels << Label.find(id)
    			end
    		end
    	end    	

    	respond_to do |fmt|
      		if @item.update_attributes(params[:item])
        		flash[:notice] = 'Item updated.'
        		fmt.html { redirect_to([:admin, @item]) }
      		else
 		    	flash[:error] = 'Problem updating item!'
		   		fmt.html { render :action => "edit" }
      		end
    	end
  	end

	 # DELETE /items/1
  	def destroy
    	@item = Item.find(params[:id])

    	respond_to do |fmt|
    		if @item.destroy
    			flash[:notice] = 'Item deleted.'
		    else
				flash[:error] = 'Problem deleting Item!'
	      	end
	      	fmt.html { redirect_to(admin_items_url) }
	    end
    end	

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	respond_to :html, :js

	def index
	    @items = Item.all
	end

	def new
		@item = Item.new
		@group_labels = Label.all		
		2.times { @item.attrs.build }
		@attr_types_map = AttrType.all.map {|at| [at.name, at.id]}
		4.times { @item.photos.build }
	end

	def show
    	@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
		@group_labels = Label.find(:all, :conditions => ['group_id = ?', @item.group.id])
		@item_label_ids = @item.labels.all.collect {|il| il.id}
		2.times { @item.attrs.build }
		@attr_types_map = AttrType.all.map {|at| [at.name, at.id]}
		4.times { @item.photos.build }

	end
	
	def create
		@item = Item.create(params[:item])

	    respond_to do |fmt|
			if @item.save
			   		flash[:notice] = 'Item created.'
		        	fmt.html { redirect_to(@item) }
		    else 
		    	flash[:error] = 'Problem saving the item!'
		    	fmt.html { render :action => "new" }
	    	end
        end
 
	end

  	# PUT /items/1
  	def update
    	@item = Item.find(params[:id])

	    if params[:prev_label_ids]
	    	prev_label_ids = params[:prev_label_ids].keys {|id| id.to_i}
	    end    	
    	if params[:curr_label_ids]
	    	curr_label_ids = params[:curr_label_ids].keys {|id| id.to_i}
	    end
	    
    	if prev_label_ids
    		prev_label_ids.each do |id|
    			unless curr_label_ids and curr_label_ids.include?(id)
    				@item.labels.delete Label.find(id)
    			end
    		end
    	end
    	if curr_label_ids
    		curr_label_ids.each do |id|
    			unless prev_label_ids and prev_label_ids.include?(id)
    				@item.labels << Label.find(id)
    			end
    		end
    	end    	

    	respond_to do |fmt|
      		if @item.update_attributes(params[:item])
        		flash[:notice] = 'item updated.'
        		fmt.html { redirect_to(@item) }
      		else
 		    	flash[:error] = 'Problem updating item!'
		   		fmt.html { render :action => "edit" }
      		end
    	end
  	end

	 # DELETE /items/1
  	def destroy
    	@item = Item.find(params[:id])

    	respond_to do |fmt|
    		if @item.destroy
    			flash[:notice] = 'Item deleted.'
		    else
				flash[:error] = 'Problem deleting Item!'
	      	end
	      	fmt.html { redirect_to(items_url) }
	    end
    end	

    def refresh_group_labels
			@group_labels = Label.find(:all, :conditions => ['group_id = ?', params[:group_id]])
    	# @item = Item.find(params[:item_id])
			# @item_label_ids = @item.labels.all.collect {|il| il.id}
			# render :partial => 'group_labels'

    	# flash[:notice] = "Got list of goups" if @group_labels
    	# respond_with( render(:partial => 'group_labels'), :layout => !request.xhr? )

			# respond_with do |wants|
	  		# wants.js {render :layout => false}

			#   wants.html do
			#     if request.xhr?
			#       render :partial => "group_labels"
			#     else
			#       render
			#     end
			#   end
			# end

    	respond_to do |fmt|
    		fmt.html {render :partial => "group_labels"}
	  		# fmt.js {render :layout => false}
			end

    end

end

app/views/admin/items/_errors.html.haml
-# Errors
- if @item.errors.any?
	%ul 
		- @item.errors.full_messages.each do |msg|
			%li #{msg} 

app/views/admin/items/_form.html.haml
= form_for [:admin, @item], :html => { :multipart => true } do |f|
	
	-# Groups
	%hr
	%h3
		Group
	%p
		- Group.all.each do |grp|
			= f.radio_button :group_id, grp.id
			= f.label :group_id, grp.name, :value => grp.id
			&nbsp;&nbsp;
		= link_to '', refresh_group_labels_admin_items_path(:item_id => @item.id, :selected_group_id => ""), :remote => true, :id => 'refresh-labels-link'
	
	#ajaxmsg	

	%hr
	%h3
		Labels
	%p#group-labels
		- unless @item_label_ids.blank?
			= render 'group_labels'

	%hr
	%h3
		Details
	%p
		= f.label :name
		= f.text_field :name
		&nbsp;&nbsp;
		= f.label :price
		= f.text_field :price
	%p
		= f.label :descr, 'Description'
		%br
		= f.text_area :descr, :rows => 4

	%hr
	-# Attributes
	%h3
		Attributes
	= f.fields_for :attrs do |sf|
		%p
			= sf.label "attr_type_id", "Type"
			= sf.select "attr_type_id", @attr_types_map
			= sf.label :detail
			= sf.text_field :detail

	%hr
	-# Photos
	%h3
		Photos
	= f.fields_for :photos do |sf|
		%p
			= sf.label :img, 'Add/Replace'
			= sf.file_field :img
			= image_tag(sf.object.img.url(:thumb))
			&nbsp;&nbsp;
			= sf.check_box :_destroy
			= sf.label :_destroy, 'Delete'


	%hr
	%p=f.submit 'Submit'

app/views/admin/items/_group_labels.html.haml
- unless @group_labels.blank?
	- @group_labels.each do |gl|
		- checkIt = @item_label_ids.include?(gl.id) if @item_label_ids
		=check_box_tag "curr_label_ids[#{gl.id}]", true, checkIt 
		=label_tag "curr_label_ids[#{gl.id}]", gl.name
		&nbsp;&nbsp;

	- if @item_label_ids
		- @item_label_ids.each do |id|
			=hidden_field_tag "prev_label_ids[#{id}]", id
- else
	No Labels exist for the selected Group - add some!

app/views/admin/items/edit.html.haml
= render 'errors'

%h1 Edit Item

= render "form"

%p
	= link_to '<< Cancel', admin_item_path( @item )	
	|
	= link_to 'Show All', admin_items_path

app/views/admin/items/index.html.haml
%h1 
	All Items

%table
	- if @items
		- @items.each do |item|
			%tr
				%td
					- if item.group 
						= item.group.name
					- else
						*none*
				%td
					- if item.photos[0]
						= link_to image_tag(item.photos[0].img.url(:thumb)), [:admin, item]
					- else
						&nbsp;
				%td
					= link_to(item.name, edit_admin_item_path(item))	
	- else
		%tr
			%td
				No Records...

%p
	= link_to('Add New', new_admin_item_path)


			

app/views/admin/items/new.html.haml
= render 'errors'

%h1 New Item

= render "form"

%p
	= link_to 'Show All', admin_items_path

app/views/admin/items/show.html.haml
%h1
	Item
%p
	Group: #{@item.group.name}
%p
	Name: #{@item.name}

%p
	Description: #{@item.descr}
%p
	Price: #{@item.price}

%p
	Photos:
	%br
	- for photo in @item.photos
		= link_to image_tag(photo.img.url(:medium)), photo.img.url(:original)

%p
	Labels:
	%br
	- for label in @item.labels
		= label.name
		&nbsp;

%p
	= link_to 'Show All', admin_items_path
	|
	= link_to 'Add New', new_admin_item_path
	|
	= link_to 'Edit', edit_admin_item_path(@item)
	|
	= link_to 'Delete', [:admin, @item], :confirm => 'Delete it?', :method => :delete