config/routes.rb
  Rienscrafts::Application.routes.draw do
  
  root :to => "site#index"
  match '/admin/vhod' => 'admin/menu#index'
  match 'labelitems' => 'site#label_items'  
  match 'groupitems' => 'site#group_items'  
  match 'itemshow' => 'site#item_show'  

  devise_for :users
  
  resources :users, :only => :show
  
  namespace :admin do

    resources :home, :labels, :attr_types, :users

    resources :items do
      collection do
        get 'refresh_group_labels'
      end
    end

  end

   match ':controller(/:action(/:id(.:format)))'
end

app/controllers/admin/attr_types_controller.rb
class Admin::AttrTypesController < ApplicationController
	before_filter :authenticate_user!
	
	def index
	    @attr_types = AttrType.all
	end

	def new
		@attr_type = AttrType.new

	end

	def create
		@attr_type = AttrType.create(params[:attr_type])

	    respond_to do |fmt|
			if @attr_type.save
			   	flash[:notice] = 'New Attribute Type created.'
		        fmt.html { redirect_to([:admin, @attr_type]) }
		    else 
		    	flash[:error] = 'Problem creating Attribute Type!'
		    	fmt.html { render :action => "new" }
	    	end
        end
	end

  	# PUT /attr_types/1
  	def update
    	@attr_type = AttrType.find(params[:id])

    	respond_to do |fmt|
      		if @attr_type.update_attributes(params[:attr_type])
        		flash[:notice] = 'Attribute Type updated.'
        		fmt.html { redirect_to([:admin, @attr_type]) }
      		else
 		    	flash[:error] = 'Problem updating Attribute Type!'
		   		fmt.html { render :action => "edit" }
      		end
    	end
  	end

	def show
    	@attr_type = AttrType.find(params[:id])
	end

	def edit
    	@attr_type = AttrType.find(params[:id])
	end

	 # DELETE /attr_types/1
  	def destroy
    	@attr_type = AttrType.find(params[:id])
    	respond_to do |fmt|
    		if @attr_type.destroy
    			flash[:notice] = 'Attribute Type deleted.'
		    else
				flash[:error] = 'Problem deleting Attribute Type!'
	      	end
	      	fmt.html { redirect_to(admin_attr_types_url) }
	    end
    end

end

app/controllers/attr_types_controller.rb
class AttrTypesController < ApplicationController
	def index
	    @attr_types = AttrType.all
	end

	def new
		@attr_type = AttrType.new

	end

	def create
		@attr_type = AttrType.create(params[:attr_type])

	    respond_to do |fmt|
			if @attr_type.save
			   	flash[:notice] = 'New Attribute Type created.'
		        fmt.html { redirect_to(@attr_type) }
		    else 
		    	flash[:error] = 'Problem creating Attribute Type!'
		    	fmt.html { render :action => "new" }
	    	end
        end
	end

  	# PUT /attr_types/1
  	def update
    	@attr_type = AttrType.find(params[:id])

    	respond_to do |fmt|
      		if @attr_type.update_attributes(params[:attr_type])
        		flash[:notice] = 'Attribute Type updated.'
        		fmt.html { redirect_to(@attr_type) }
      		else
 		    	flash[:error] = 'Problem updating Attribute Type!'
		   		fmt.html { render :action => "edit" }
      		end
    	end
  	end

	def show
    	@attr_type = AttrType.find(params[:id])
	end

	def edit
    	@attr_type = AttrType.find(params[:id])
	end

	 # DELETE /attr_types/1
  	def destroy
    	@attr_type = AttrType.find(params[:id])
    	respond_to do |fmt|
    		if @attr_type.destroy
    			flash[:notice] = 'Attribute Type deleted.'
		    else
				flash[:error] = 'Problem deleting Attribute Type!'
	      	end
	      	fmt.html { redirect_to(attr_types_url) }
	    end
    end

end

app/views/admin/attr_types/_form.html.haml
= form_for [:admin, @attr_type] do |f|
	/= f.error_messages
	%p
		= f.label :name
		= f.text_field :name
	%br
	=f.submit 'Submit'

app/views/admin/attr_types/edit.html.haml
%h1 Edit Attribute Type
= render "form"

%p
	= link_to '<< Cancel', admin_attr_type_path( @attr_type )	
	|
	= link_to 'Show All', admin_attr_types_path

app/views/admin/attr_types/index.html.haml
%h1 
	All Attribute Types

- if @attr_types
	%ul
		- @attr_types.each do |at|
			%li= link_to(at.name, admin_attr_type_path(at))	
- else
	No Records...

%p
	= link_to('Add New', new_admin_attr_type_path)


			

app/views/admin/attr_types/new.html.haml
%h1 New Attribute Type

= render "form"

= link_to 'Show All', admin_attr_types_path

app/views/admin/attr_types/show.html.haml
%h1
	Attribute Type
%p
	Name: #{@attr_type.name}

%p
	= link_to 'Show All', admin_attr_types_path
	|
	= link_to 'Add New', new_admin_attr_type_path
	|
	= link_to 'Edit', edit_admin_attr_type_path(@attr_type)
	|
	= link_to 'Delete', [:admin, @attr_type], :confirm => 'Delete it?', :method => :delete