config/routes.rb
  Rienscrafts::Application.routes.draw do
  
  root :to => "site#index"
  match '/admin/vhod' => 'admin/menu#index'
  match 'labelitems' => 'site#label_items'  
  match 'groupitems' => 'site#group_items'  
  match 'itemshow' => 'site#item_show'  

  devise_for :users
  
  resources :users, :only => :show
  
  namespace :admin do

    resources :home, :labels, :attr_types, :users

    resources :items do
      collection do
        get 'refresh_group_labels'
      end
    end

  end

   match ':controller(/:action(/:id(.:format)))'
end

app/models/label.rb
class Label < ActiveRecord::Base
		has_and_belongs_to_many :items#, :unique => true
		belongs_to :group

		validates :group_id, :presence => true
		validates :name, :presence => true, :length => {:minimum => 3}
end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < ApplicationController
	before_filter :authenticate_user!

	def index
	    @labels = Label.all
	end

	def new
		@label = Label.new
		@groups = Group.all
	end

	def show
    	@label = Label.find(params[:id])
	end

	def edit
    	@label = Label.find(params[:id])
    	@groups = Group.all
	end

	def create
		@label = Label.create(params[:label])

	    respond_to do |fmt|
			if @label.save
			   	flash[:notice] = 'Label created.'
		        fmt.html { redirect_to([:admin, @label]) }
		    else 
		    	flash[:error] = 'Problem updating label!'
		    	fmt.html { render :action => "new" }
	    	end
        end
 
	end
  	# PUT /labels/1
  	def update
    	@label = Label.find(params[:id])

    	respond_to do |fmt|
      		if @label.update_attributes(params[:label])
        		flash[:notice] = 'Label updated.'
        		fmt.html { redirect_to([:admin, @label]) }
      		else
 		    	flash[:error] = 'Problem updating Label!'
		   		fmt.html { render :action => "edit" }
      		end
    	end
  	end

	 # DELETE /labels/1
  	def destroy
    	@label = Label.find(params[:id])

    	respond_to do |fmt|
    		if @label.destroy
    			flash[:notice] = 'Label deleted.'
		    else
				flash[:error] = 'Problem deleting Label!'
	      	end
	      	fmt.html { redirect_to(admin_labels_url) }
	    end
    end	

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
	def index
	    @labels = Label.all
	end

	def new
		@label = Label.new
		@groups = Group.all
	end

	def show
    	@label = Label.find(params[:id])
	end

	def edit
    	@label = Label.find(params[:id])
    	@groups = Group.all
	end

	def create
		@label = Label.create(params[:label])

	    respond_to do |fmt|
			if @label.save
			   	flash[:notice] = 'Label created.'
		        fmt.html { redirect_to(@label) }
		    else 
		    	flash[:error] = 'Problem updating label!'
		    	fmt.html { render :action => "new" }
	    	end
        end
 
	end
  	# PUT /labels/1
  	def update
    	@label = Label.find(params[:id])

    	respond_to do |fmt|
      		if @label.update_attributes(params[:label])
        		flash[:notice] = 'Label updated.'
        		fmt.html { redirect_to(@label) }
      		else
 		    	flash[:error] = 'Problem updating Label!'
		   		fmt.html { render :action => "edit" }
      		end
    	end
  	end

	 # DELETE /labels/1
  	def destroy
    	@label = Label.find(params[:id])

    	respond_to do |fmt|
    		if @label.destroy
    			flash[:notice] = 'Label deleted.'
		    else
				flash[:error] = 'Problem deleting Label!'
	      	end
	      	fmt.html { redirect_to(labels_url) }
	    end
    end	

end

app/views/admin/labels/_errors.html.haml
-# Errors
- if @label.errors.any?
	%ul 
		- @label.errors.full_messages.each do |msg|
			%li #{msg} 

app/views/admin/labels/_form.html.haml
= form_for [:admin, @label] do |f|
	%div
		Group:
		%ul
			- Group.all.each do |grp|
				%li
					= f.radio_button :group_id, grp.id
					= f.label :group_id, grp.name, :value => grp.id

	%div
		= f.label :name
		= f.text_field :name

	%p=f.submit 'Submit'

app/views/admin/labels/edit.html.haml
= render "errors"

%h1 Edit Label

= render "form"

%p
	= link_to '<< Cancel', admin_label_path( @label )	
	|
	= link_to 'Show All', admin_labels_path

app/views/admin/labels/index.html.haml
%h1 
	All Labels

- if @labels
	%ul
		- @labels.each do |at|
			%li
				= at.group.name 
				-
				= link_to(at.name, admin_label_path(at))	
- else
	No Records...

%p
	= link_to('Add New', new_admin_label_path)

app/views/admin/labels/new.html.haml
= render "errors"

%h1 New Label

= render "form"

= link_to 'Show All', admin_labels_path

app/views/admin/labels/show.html.haml
%h1
	Label
%p
	Group: #{@label.group.name}
%p
	Name: #{@label.name}

%p
	= link_to 'Show All', admin_labels_path
	|
	= link_to 'Add New', new_admin_label_path
	|
	= link_to 'Edit', edit_admin_label_path(@label)
	|
	= link_to 'Delete', [:admin, @label], :confirm => 'Delete it?', :method => :delete