config/routes.rb
  Rienscrafts::Application.routes.draw do
  
  root :to => "site#index"
  match '/admin/vhod' => 'admin/menu#index'
  match 'labelitems' => 'site#label_items'  
  match 'groupitems' => 'site#group_items'  
  match 'itemshow' => 'site#item_show'  

  devise_for :users
  
  resources :users, :only => :show
  
  namespace :admin do

    resources :home, :labels, :attr_types, :users

    resources :items do
      collection do
        get 'refresh_group_labels'
      end
    end

  end

   match ':controller(/:action(/:id(.:format)))'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def index
		@groups = Group.all
	end

	def label_items
		@groups = Group.all
		@label = Label.find(params[:label_id])
		@group = @label.group
		@group_labels = Label.find :all, :conditions => ["group_id=?", @group.id]
		@items = @label.items
		render 'items'
	end

	def group_items
		@groups = Group.all
		@group = Group.find(params[:group_id])
		@group_labels = Label.find :all, :conditions => ["group_id=?", @group.id]
		@items = @group.items  
		render 'items'
	end

	def item_show
		@item = Item.find params[:id]
		@groups = Group.all
		@group = @item.group		
		@group_labels = Label.find :all, :conditions => ["group_id=?", @group.id]
	end

end

app/views/site/_menu.html.haml
- if user_signed_in?
  %li
    = link_to('Admin', '/admin/menu')

app/views/site/_tab_labels.html.haml
#tab-side-wrap
	.tab-conn-horiz

	.tab-labels.tab-active
		- if @group_labels
			%ul
				- @group_labels.each do |lbl|
					%li
						= link_to lbl.name, labelitems_path(:label_id => lbl.id) 
						- if (lbl === @label)
							= image_tag('button.png', :height => '20px', :width => '20px')

app/views/site/_tabs_groups.html.haml
#tabs-groups
	- @groups.each do |grp|
		.tab-wrap
			- if @group == grp
				.tab-group.tab-active.framed
					= grp.name
					= image_tag('button.png', :height => '18px', :width => '18px')
				.tab-conn-vert

			- else
				.tab-group.tab-inactive.framed
					= link_to grp.name, groupitems_path(:group_id => grp.id)
			

app/views/site/index.html.haml
#tabs
	#tabs-groups
		- @groups.each do |grp|
			.tab-wrap
				.tab-group.tab-inactive
					= link_to grp.name, groupitems_path(:group_id => grp.id)
				.tab-conn-vert
				.tab-group.tab-inactive
					%ul
						- grp.labels.each do |lbl|
							%li.group-labels
								= link_to lbl.name, labelitems_path(:label_id => lbl.id) 


#carousel_wrap
	%ul#banners.jcarousel-skin-banners
		%li
			=image_tag("banner1.jpg", :height => "120px")
		%li
			=image_tag("banner2.jpg", :height => "120px")
		%li
			=image_tag("banner3.jpg", :height => "120px")
		%li
			=image_tag("banner4.jpg", :height => "120px")
		%li
			=image_tag("banner5.jpg", :height => "120px")
		%li
			=image_tag("banner6.jpg", :height => "120px")
		%li
			=image_tag("banner7.jpg", :height => "120px")
		%li
			=image_tag("banner8.jpg", :height => "120px")
		%li
			=image_tag("banner9.jpg", :height => "120px")
		%li
			=image_tag("banner10.jpg", :height => "120px")
		%li
			=image_tag("banner11.jpg", :height => "120px")
		%li
			=image_tag("banner12.jpg", :height => "120px")

app/views/site/item_show.html.haml
#tabs
	= render 'tabs_groups'

	#tab-content.tab-active.framed
		%p
			= @item.name
		%p
			= @item.descr
		%p
			Price: $#{@item.price}

		%div 
			- @item.photos.each do |photo|
				= link_to image_tag(photo.img.url(:medium), :title => @item.name), photo.img.url, :rel => 'gallery'

	= render "tab_labels"

app/views/site/items.html.haml
#tabs
	= render 'tabs_groups'

	#tab-content.tab-active

		- if @items
			- @items.each do |item|
				.list_item 
					- photo = item.photos[0]
					= link_to image_tag(photo.img.url(:medium), :title => item.name), itemshow_path(:id => item.id)
					%br
					= item.name

	= render "tab_labels"